"""Dynamic marginal-surface detectors for closed and brane-spanning classes.

The spatial slice is the regular SO(3) ADM reduction already audited by the
donor-capped detector.  A surface is generated by a meridional curve
``x(u)=(z(u),r(u))`` times a round two-sphere.  This module evaluates

``theta_+ = D_i s^i + K_ij s^i s^j - K``

from the covariant acceleration of that curve.  It supports star-shaped
closed ``S3`` profiles and interval-spanning ``S2 x I`` radial graphs.  A
normal-derivative evaluator and nodal finite-difference/Newton solvers provide
checks independent of the adaptive local-BVP discretization.
"""

from __future__ import annotations

import numpy as np
from scipy.integrate import solve_bvp
from scipy.interpolate import CubicSpline
from scipy.optimize import root

from bhps.dynamical_capped_horizon import prepare_capped_expansion_slice


def _sample_curve_geometry(prepared, zcoord, radius, first):
    """Sample the ADM fields and normalize a meridional tangent/normal."""
    zcoord = np.asarray(zcoord, dtype=float)
    radius = np.asarray(radius, dtype=float)
    first = np.asarray(first, dtype=float)
    sample_z = np.clip(zcoord, prepared.z[0], prepared.z[-1])
    sample_r = np.clip(radius, prepared.r[0], prepared.r[-1])
    count = len(zcoord)
    metric = np.empty((count, 2, 2))
    inverse = np.empty_like(metric)
    connection = np.empty((count, 2, 2, 2))
    log_gradient = np.empty((count, 2))
    extrinsic = np.empty_like(metric)
    for left in range(2):
        log_gradient[:, left] = prepared.sample(
            ("log_transverse_scale_gradient", left), sample_z, sample_r,
        )
        for right in range(2):
            metric[:, left, right] = prepared.sample(
                ("base_metric", left, right), sample_z, sample_r,
            )
            inverse[:, left, right] = prepared.sample(
                ("base_inverse", left, right), sample_z, sample_r,
            )
            extrinsic[:, left, right] = prepared.sample(
                ("extrinsic_base", left, right), sample_z, sample_r,
            )
            for upper in range(2):
                connection[:, upper, left, right] = prepared.sample(
                    ("base_connection", upper, left, right), sample_z, sample_r,
                )
    sphere_extrinsic = prepared.sample(
        ("extrinsic_sphere_eigenvalue",), sample_z, sample_r,
    )
    log_gradient[:, 1] += 1.0 / np.maximum(np.abs(radius), 1e-12)
    speed_squared = np.einsum("...a,...ab,...b->...", first, metric, first)
    speed_squared = np.maximum(speed_squared, 1e-24)
    speed = np.sqrt(speed_squared)
    tangent = first / speed[:, None]
    # For increasing curve parameter this is the outward normal used by both
    # supported parameterizations: radial-outward for r=R(z), and polar-
    # outward for z=zc-rho*cos(theta), r=rho*sin(theta).
    normal_covector = np.stack((-first[:, 1], first[:, 0]), axis=1)
    normal_norm_squared = np.einsum(
        "...a,...ab,...b->...", normal_covector, inverse, normal_covector,
    )
    normal_covector /= np.sqrt(np.maximum(normal_norm_squared, 1e-24))[:, None]
    normal = np.einsum("...ab,...b->...a", inverse, normal_covector)
    return {
        "connection": connection,
        "log_gradient": log_gradient,
        "extrinsic": extrinsic,
        "sphere_extrinsic": sphere_extrinsic,
        "tangent": tangent,
        "normal": normal,
        "normal_covector": normal_covector,
        "speed": speed,
        "speed_squared": speed_squared,
    }


def local_curve_outgoing_expansion(prepared, zcoord, radius, first, second):
    """Evaluate the local expansion from ``x'`` and ``x''``."""
    geometry = _sample_curve_geometry(prepared, zcoord, radius, first)
    second = np.asarray(second, dtype=float)
    curve = -np.einsum(
        "...a,...a->...", geometry["normal_covector"], second,
    ) / geometry["speed_squared"]
    curve -= np.einsum(
        "...a,...b,...cab,...c->...",
        geometry["tangent"], geometry["tangent"], geometry["connection"],
        geometry["normal_covector"],
    )
    sphere = 2.0 * np.einsum(
        "...a,...a->...", geometry["normal"], geometry["log_gradient"],
    )
    tangent_extrinsic = np.einsum(
        "...a,...ab,...b->...",
        geometry["tangent"], geometry["extrinsic"], geometry["tangent"],
    )
    correction = -tangent_extrinsic - 2.0 * geometry["sphere_extrinsic"]
    return curve + sphere + correction


def sampled_normal_derivative_expansion(prepared, parameter, zcoord, radius, first):
    """Independently evaluate expansion by differentiating the unit normal."""
    parameter = np.asarray(parameter, dtype=float)
    geometry = _sample_curve_geometry(prepared, zcoord, radius, first)
    normal_derivative = np.gradient(
        geometry["normal_covector"], parameter, axis=0, edge_order=2,
    )
    curve = np.einsum(
        "...a,...a->...", geometry["tangent"], normal_derivative,
    ) / geometry["speed"]
    curve -= np.einsum(
        "...a,...b,...cab,...c->...",
        geometry["tangent"], geometry["tangent"], geometry["connection"],
        geometry["normal_covector"],
    )
    sphere = 2.0 * np.einsum(
        "...a,...a->...", geometry["normal"], geometry["log_gradient"],
    )
    tangent_extrinsic = np.einsum(
        "...a,...ab,...b->...",
        geometry["tangent"], geometry["extrinsic"], geometry["tangent"],
    )
    return curve + sphere - tangent_extrinsic - 2.0 * geometry["sphere_extrinsic"]


def _polar_curve(theta, rho, slope, second):
    sine = np.sin(theta)
    cosine = np.cos(theta)
    first = np.stack((
        rho * sine - slope * cosine,
        rho * cosine + slope * sine,
    ), axis=1)
    acceleration = np.stack((
        rho * cosine + 2.0 * slope * sine - second * cosine,
        -rho * sine + 2.0 * slope * cosine + second * sine,
    ), axis=1)
    return first, acceleration


def closed_local_expansion(prepared, z_center, theta, rho, slope, second):
    """Expansion of a closed polar graph about ``z_center``."""
    theta = np.asarray(theta, dtype=float)
    rho = np.asarray(rho, dtype=float)
    slope = np.asarray(slope, dtype=float)
    second = np.asarray(second, dtype=float)
    radius = rho * np.sin(theta)
    zcoord = float(z_center) - rho * np.cos(theta)
    first, acceleration = _polar_curve(theta, rho, slope, second)
    return local_curve_outgoing_expansion(
        prepared, zcoord, radius, first, acceleration,
    )


def _affine_second(offset, unit):
    coefficient = unit - offset
    return np.divide(
        -offset, coefficient, out=np.full_like(offset, np.nan),
        where=np.abs(coefficient) > 1e-12,
    )


def closed_rho_second(prepared, z_center, theta, rho, slope):
    zero = np.zeros_like(np.asarray(rho, dtype=float))
    offset = closed_local_expansion(
        prepared, z_center, theta, rho, slope, zero,
    )
    unit = closed_local_expansion(
        prepared, z_center, theta, rho, slope, np.ones_like(zero),
    )
    return _affine_second(offset, unit)


def _closed_diagnostics(
    prepared, z_center, theta, rho, slope, second, solver_success,
    message, iterations=0, mesh_nodes_used=0,
):
    radius = rho * np.sin(theta)
    zcoord = float(z_center) - rho * np.cos(theta)
    first, _ = _polar_curve(theta, rho, slope, second)
    local = closed_local_expansion(
        prepared, z_center, theta, rho, slope, second,
    )
    independent = sampled_normal_derivative_expansion(
        prepared, theta, zcoord, radius, first,
    )
    dz = float(np.min(np.diff(prepared.z)))
    dr = float(np.min(np.diff(prepared.r)))
    interior = (
        (radius >= 2.0 * dr)
        & (zcoord >= prepared.z[0] + 2.0 * dz)
        & (zcoord <= prepared.z[-1] - 2.0 * dz)
    )
    in_domain = bool(
        np.min(rho) > 2.0 * dr
        and np.min(zcoord) > prepared.z[0] + 2.0 * dz
        and np.max(zcoord) < prepared.z[-1] - 2.0 * dz
        and np.max(radius) < 0.9 * prepared.r[-1]
    )
    local_maximum = float(
        np.max(np.abs(local[interior])) if np.any(interior) else np.inf
    )
    independent_maximum = float(
        np.max(np.abs(independent[interior])) if np.any(interior) else np.inf
    )
    boundary_error = float(max(abs(slope[0]), abs(slope[-1])))
    return {
        "converged": bool(
            solver_success and in_domain and np.any(interior)
            and local_maximum < 2e-4 and boundary_error < 2e-4
        ),
        "solver_success": bool(solver_success),
        "message": str(message),
        "in_domain": in_domain,
        "iterations": int(iterations),
        "mesh_nodes_used": int(mesh_nodes_used),
        "z_center": float(z_center),
        "theta": theta,
        "rho": rho,
        "slope": slope,
        "z_lower_tip": float(zcoord[0]),
        "z_upper_tip": float(zcoord[-1]),
        "radius_max": float(np.max(radius)),
        "rho_min": float(np.min(rho)),
        "rho_max": float(np.max(rho)),
        "boundary_slope_error": boundary_error,
        "local_expansion_interior_maximum": local_maximum,
        "independent_expansion_interior_maximum": independent_maximum,
        "interior_point_count": int(np.count_nonzero(interior)),
    }


def solve_dynamical_closed_surface_bvp(
    position, velocity, z, r, z_center, initial, tolerance=2e-5,
    nodes=121, maximum_nodes=6000, dense_nodes=601, stencil_width=7,
    prepared=None,
):
    """Adaptive local-BVP solve for one closed star-shaped ``S3``."""
    z = np.asarray(z, dtype=float)
    r = np.asarray(r, dtype=float)
    prepared = (
        prepare_capped_expansion_slice(position, velocity, z, r, stencil_width)
        if prepared is None else prepared
    )
    theta = np.linspace(1e-4, np.pi - 1e-4, int(nodes))
    if np.isscalar(initial):
        values = np.vstack((
            np.full_like(theta, float(initial)), np.zeros_like(theta),
        ))
    else:
        source = np.asarray(initial["theta"], dtype=float)
        values = np.vstack((
            np.interp(theta, source, np.asarray(initial["rho"], dtype=float)),
            np.interp(
                theta, source,
                np.asarray(initial.get("slope", np.zeros_like(source)), dtype=float),
            ),
        ))

    def equation(angle, state):
        return np.vstack((
            state[1],
            closed_rho_second(prepared, z_center, angle, state[0], state[1]),
        ))

    solved = solve_bvp(
        equation, lambda left, right: np.array((left[1], right[1])),
        theta, values, tol=float(tolerance), max_nodes=int(maximum_nodes),
        verbose=0,
    )
    dense = np.linspace(theta[0], theta[-1], int(dense_nodes))
    values = solved.sol(dense)
    derivatives = solved.sol(dense, 1)
    result = _closed_diagnostics(
        prepared, z_center, dense, values[0], values[1], derivatives[1],
        solved.success, solved.message, solved.niter, len(solved.x),
    )
    result["ode_defect_maximum"] = float(
        np.max(np.abs(derivatives - equation(dense, values)))
    )
    return result


def spanning_local_expansion(prepared, zcoord, radius, slope, second):
    """Expansion of an interval-spanning radial graph ``r=R(z)``."""
    zcoord = np.asarray(zcoord, dtype=float)
    radius = np.asarray(radius, dtype=float)
    slope = np.asarray(slope, dtype=float)
    second = np.asarray(second, dtype=float)
    first = np.stack((np.ones_like(slope), slope), axis=1)
    acceleration = np.stack((np.zeros_like(second), second), axis=1)
    return local_curve_outgoing_expansion(
        prepared, zcoord, radius, first, acceleration,
    )


def spanning_radius_second(prepared, zcoord, radius, slope):
    zero = np.zeros_like(np.asarray(radius, dtype=float))
    offset = spanning_local_expansion(prepared, zcoord, radius, slope, zero)
    unit = spanning_local_expansion(
        prepared, zcoord, radius, slope, np.ones_like(zero),
    )
    return _affine_second(offset, unit)


def _spanning_diagnostics(
    prepared, zcoord, radius, slope, second, solver_success, message,
    iterations=0, mesh_nodes_used=0,
):
    first = np.stack((np.ones_like(slope), slope), axis=1)
    local = spanning_local_expansion(
        prepared, zcoord, radius, slope, second,
    )
    independent = sampled_normal_derivative_expansion(
        prepared, zcoord, zcoord, radius, first,
    )
    dz = float(np.min(np.diff(prepared.z)))
    dr = float(np.min(np.diff(prepared.r)))
    interior = (
        (zcoord >= prepared.z[0] + 2.0 * dz)
        & (zcoord <= prepared.z[-1] - 2.0 * dz)
        & (radius >= 2.0 * dr)
    )
    in_domain = bool(
        np.min(radius) > 2.0 * dr and np.max(radius) < 0.9 * prepared.r[-1]
    )
    local_maximum = float(
        np.max(np.abs(local[interior])) if np.any(interior) else np.inf
    )
    independent_maximum = float(
        np.max(np.abs(independent[interior])) if np.any(interior) else np.inf
    )
    boundary_error = float(max(abs(slope[0]), abs(slope[-1])))
    return {
        "converged": bool(
            solver_success and in_domain and np.any(interior)
            and local_maximum < 2e-4 and boundary_error < 2e-4
        ),
        "solver_success": bool(solver_success),
        "message": str(message),
        "in_domain": in_domain,
        "iterations": int(iterations),
        "mesh_nodes_used": int(mesh_nodes_used),
        "z": zcoord,
        "radius": radius,
        "slope": slope,
        "radius_A": float(radius[0]),
        "radius_B": float(radius[-1]),
        "radius_min": float(np.min(radius)),
        "radius_max": float(np.max(radius)),
        "boundary_slope_error": boundary_error,
        "local_expansion_interior_maximum": local_maximum,
        "independent_expansion_interior_maximum": independent_maximum,
        "interior_point_count": int(np.count_nonzero(interior)),
    }


def solve_dynamical_spanning_surface_bvp(
    position, velocity, z, r, initial, tolerance=2e-5, nodes=121,
    maximum_nodes=6000, dense_nodes=501, stencil_width=7, prepared=None,
):
    """Adaptive local-BVP solve for one brane-spanning ``S2 x I`` graph."""
    z = np.asarray(z, dtype=float)
    r = np.asarray(r, dtype=float)
    prepared = (
        prepare_capped_expansion_slice(position, velocity, z, r, stencil_width)
        if prepared is None else prepared
    )
    mesh = np.linspace(z[0], z[-1], int(nodes))
    if np.isscalar(initial):
        values = np.vstack((
            np.full_like(mesh, float(initial)), np.zeros_like(mesh),
        ))
    else:
        source = np.asarray(initial["z"], dtype=float)
        values = np.vstack((
            np.interp(mesh, source, np.asarray(initial["radius"], dtype=float)),
            np.interp(
                mesh, source,
                np.asarray(initial.get("slope", np.zeros_like(source)), dtype=float),
            ),
        ))

    def equation(compact, state):
        return np.vstack((
            state[1],
            spanning_radius_second(prepared, compact, state[0], state[1]),
        ))

    solved = solve_bvp(
        equation, lambda left, right: np.array((left[1], right[1])),
        mesh, values, tol=float(tolerance), max_nodes=int(maximum_nodes),
        verbose=0,
    )
    dense = np.linspace(z[0], z[-1], int(dense_nodes))
    values = solved.sol(dense)
    derivatives = solved.sol(dense, 1)
    result = _spanning_diagnostics(
        prepared, dense, values[0], values[1], derivatives[1],
        solved.success, solved.message, solved.niter, len(solved.x),
    )
    result["ode_defect_maximum"] = float(
        np.max(np.abs(derivatives - equation(dense, values)))
    )
    return result


def _closed_fd_residual(values, theta, prepared, z_center):
    values = np.asarray(values, dtype=float)
    spacing = float(theta[1] - theta[0])
    output = np.zeros_like(values)
    output[0] = (-3.0 * values[0] + 4.0 * values[1] - values[2]) / (2.0 * spacing)
    output[-1] = (3.0 * values[-1] - 4.0 * values[-2] + values[-3]) / (2.0 * spacing)
    slope = (values[2:] - values[:-2]) / (2.0 * spacing)
    second = (values[2:] - 2.0 * values[1:-1] + values[:-2]) / spacing**2
    output[1:-1] = closed_local_expansion(
        prepared, z_center, theta[1:-1], values[1:-1], slope, second,
    )
    return output


def solve_dynamical_closed_surface_fd(
    position, velocity, z, r, z_center, initial, nodes=101,
    tolerance=1e-9, maximum_evaluations=6000, stencil_width=7, prepared=None,
):
    """Independent nodal finite-difference/Newton closed-surface solve."""
    z = np.asarray(z, dtype=float)
    r = np.asarray(r, dtype=float)
    prepared = (
        prepare_capped_expansion_slice(position, velocity, z, r, stencil_width)
        if prepared is None else prepared
    )
    theta = np.linspace(1e-4, np.pi - 1e-4, int(nodes))
    guess = (
        np.full_like(theta, float(initial)) if np.isscalar(initial)
        else np.interp(theta, np.asarray(initial["theta"]), np.asarray(initial["rho"]))
    )
    solved = root(
        lambda values: _closed_fd_residual(values, theta, prepared, z_center),
        guess, method="hybr",
        options={"xtol": float(tolerance), "maxfev": int(maximum_evaluations)},
    )
    discrete = float(np.max(np.abs(
        _closed_fd_residual(solved.x, theta, prepared, z_center),
    )))
    profile = CubicSpline(theta, solved.x, bc_type=((1, 0.0), (1, 0.0)))
    dense = np.linspace(theta[0], theta[-1], 601)
    result = _closed_diagnostics(
        prepared, z_center, dense, profile(dense), profile(dense, 1),
        profile(dense, 2), solved.success and discrete < 1e-6,
        solved.message, mesh_nodes_used=len(theta),
    )
    result.update({
        "discrete_residual_maximum": discrete,
        "function_evaluations": int(solved.nfev),
        "nodes": int(nodes),
    })
    return result


def _spanning_fd_residual(values, mesh, prepared):
    values = np.asarray(values, dtype=float)
    spacing = float(mesh[1] - mesh[0])
    output = np.zeros_like(values)
    output[0] = (-3.0 * values[0] + 4.0 * values[1] - values[2]) / (2.0 * spacing)
    output[-1] = (3.0 * values[-1] - 4.0 * values[-2] + values[-3]) / (2.0 * spacing)
    slope = (values[2:] - values[:-2]) / (2.0 * spacing)
    second = (values[2:] - 2.0 * values[1:-1] + values[:-2]) / spacing**2
    output[1:-1] = spanning_local_expansion(
        prepared, mesh[1:-1], values[1:-1], slope, second,
    )
    return output


def solve_dynamical_spanning_surface_fd(
    position, velocity, z, r, initial, nodes=81, tolerance=1e-9,
    maximum_evaluations=6000, stencil_width=7, prepared=None,
):
    """Independent nodal finite-difference/Newton spanning-surface solve."""
    z = np.asarray(z, dtype=float)
    r = np.asarray(r, dtype=float)
    prepared = (
        prepare_capped_expansion_slice(position, velocity, z, r, stencil_width)
        if prepared is None else prepared
    )
    mesh = np.linspace(z[0], z[-1], int(nodes))
    guess = (
        np.full_like(mesh, float(initial)) if np.isscalar(initial)
        else np.interp(mesh, np.asarray(initial["z"]), np.asarray(initial["radius"]))
    )
    solved = root(
        lambda values: _spanning_fd_residual(values, mesh, prepared), guess,
        method="hybr",
        options={"xtol": float(tolerance), "maxfev": int(maximum_evaluations)},
    )
    discrete = float(np.max(np.abs(
        _spanning_fd_residual(solved.x, mesh, prepared),
    )))
    profile = CubicSpline(mesh, solved.x, bc_type=((1, 0.0), (1, 0.0)))
    dense = np.linspace(z[0], z[-1], 501)
    result = _spanning_diagnostics(
        prepared, dense, profile(dense), profile(dense, 1), profile(dense, 2),
        solved.success and discrete < 1e-6, solved.message,
        mesh_nodes_used=len(mesh),
    )
    result.update({
        "discrete_residual_maximum": discrete,
        "function_evaluations": int(solved.nfev),
        "nodes": int(nodes),
    })
    return result
